blogSystem/blogSystem/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace blogSystem.Controllers
{
    public class ArticleController : Controller
    {
        //
        // GET: /Article/

        public ActionResult Index()
        {
            return View();
        }

    }
}

blogSystem/blogSystem/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace blogSystem.Controllers
{
    public class BookController : Controller
    {
        //
        // GET: /Book/

        public ActionResult Index()
        {
            return View();
        }

    }
}

blogSystem/blogSystem/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace blogSystem.Controllers
{
    public class CourseController : Controller
    {
        //
        // GET: /Course/

        public ActionResult Index()
        {
            return View();
        }

    }
}

blogSystem/blogSystem/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using blogSystem.Models;

namespace blogSystem.Controllers
{
    public class ProfileController : Controller
    {
        //
        // GET: /Profile/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewInfo(PerfilModel model)
        {
            ViewBag.lista = model.ViewInfo(User.Identity.Name);
            return View();
        }

    }
}

blogSystem/blogSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <!-- <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" /> -->
    <link href="@Url.Content("~/Content/Css/style.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Css/mislibros.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Css/gce-style.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body class="home blog singel-author two-column right-sidebar">
    <div id="page" class="hfeed">
        <header id="branding" role="banner">
            <hgroup>
				<div id="logo">
				    <h2 id="site-description">Contenidos Multimedia</h2>                    
			    </div>
                <div id="user">
                    @Html.Partial("_LogOnPartial")
                </div>                
			</hgroup>
            <nav id="access" role="navigation">
			    <h3 class="assistive-text">Menu principal</h3>
				<div class="skip-link">
				    <a class="assistive-text" href="#" title="Ir al contenido principal">Ir al contenido principal</a>                    
                </div>
				<div class="menu-menuprincipal-container">
					<ul id="menu-menuprincipal" class="menu">
						<li id="menu-item-1975" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-1975">
						    @Html.ActionLink("Blog","Index","Home")
						</li>
                        <li id="menu-item-2027" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2027">
							<a href="/Home/Libros">Libros</a>
						</li>
                        <li id="menu-item-2027" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2027">
							@Html.ActionLink("Tutorial","Create","Tutorial")
						</li>
                        <li id="menu-item-2027" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2027">
							<a href="/Home/Previos">Articulos</a>
						</li>
                        <li id="menu-item-2027" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2027">
							<a href="/Home/Previos">Cursos</a>
						</li>
						<li id="menu-item-2027" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2027">
							<a href="/Home/Previos">Acerca de</a>
						</li>
                        <li id="menu-item-2027" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2027">
							<a href="/Home/Previos">Contacto</a>
						</li>
					</ul>
				</div>
				<div class="only-search">
				</div>
				<div class="redesSociales">
				</div>
			</nav>
        </header> 
        <div id="main">
            <section>
                @if (IsSectionDefined("SidebarLeft"))
                {
                    <div id="sidebarLeft">
                        @RenderSection("SideBarLeft")
                        <div id="lineah"></div>
                    </div>                    
                }
                <div id="primary">
                    @RenderBody()
                </div>                 
                <div style="clear: left;">
                </div>
            </section>
            @if(IsSectionDefined("SidebarRight")){
                @RenderSection("SideBarRight")
            }
        </div>
        <footer id="colophon" role="contentinfo">
            <div id="pie">
				<div class="menu-menupie-container">
					<ul id="menu-menupie" class="menu">
						<li id="menu-item-1979" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1979">
							<a href="#">- Acerca de </a>
						</li>
						<li id="menu-item-1979" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1979">
							<a href="#">- Acerca de </a>
						</li>
						<li id="menu-item-1979" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1979">
							<a href="#">- Acerca de</a>
						</li>
					</ul>
				</div>
			</div>
        </footer>
    </div>
</body>
</html>

blogSystem/blogSystem/Views/Shared/_LogOnPartial.cshtml
<div class="btn input-small">
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>
     @Html.ActionLink("Log out", "LogOff", "Account") </text>
}
else {
     @Html.ActionLink("Login", "LogOn", "Account") 
}
</div>

blogSystem/blogSystem/Views/Shared/_SideBarLeft.cshtml
@{
    string imagen = "~/Content/images/" + @ViewBag.lista.avatar;
}
<div id="profile">
    <img src="@Url.Content(imagen)" alt="Imagen de usuario" width="130" height="130" />
    <span>
        <p>@ViewBag.lista.nombre @ViewBag.lista.apellido</p>
    </span>
</div>

<ul>
    <li>@Html.ActionLink("Información","ViewInfo","Profile")</li>
    <li>@Html.ActionLink("Libros","Index","Book")</li>
    <li>@Html.ActionLink("Tutoriales","Index","Tutorial")</li>
    <li>@Html.ActionLink("Artículos","Index","Article")</li>
    <li>@Html.ActionLink("Cursos","Index","Course")</li>
    <li>Actividades</li>
</ul>